logging:
  level:
    ROOT: DEBUG

spring:
  datasource:
    url: jdbc:p6spy:h2:mem:creator-in-app-game;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=TRUE
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver

decorator.datasource.p6spy:
  enable-logging: true
  multiline: true
  logging: slf4j
  tracing.include-parameter-values: true
