/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    // Apply the common convention plugin for shared build configuration between library and application projects.
    id("me.zepeto.creator.in_app_game.creator.kotlin-common-conventions")

    // Apply the application plugin to add support for building a CLI application in Java.
    application
}
