/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package me.zepeto.creator.in_app_game.creator.app

import me.zepeto.creator.in_app_game.creator.utilities.StringUtils

import org.apache.commons.text.WordUtils

fun main() {
    val tokens = StringUtils.split(MessageUtils.getMessage())
    val result = StringUtils.join(tokens)
    println(WordUtils.capitalize(result))
}
