/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package me.zepeto.creator.in_app_game.creator.app

class MessageUtils {
    companion object {
        fun getMessage(): String = "Hello      World!"
    }
}
